### ISSUE TITLE
Not able to access ledger Unauthorized error

### ISSUE THREAD

**Issue by THEViveKL** [interledgerjs/five-bells-ledger#431]
Hi,

After doing all the things when i execute this command on docker as follows:

> docker run -d -e LEDGER_PORT=1337 -e LEDGER_ADMIN_PASSWORD=admin -e LEDGER_DB_URI=postgres://postgres:password@db --link five-bells-ledger-db:db -p 1337:1337 -h localhost --name fivebells interledger/five-bells-ledger

It executes successfully. but when i tried for this URL it requires authentication. 

> http://localhost:1337/health

I want to know **username and password** for accessing above URL?.
i have tried with admin:admin which is given in curl command.
but got same  "**Unauthorized error**" .

> curl -i -sS -X PUT --user admin:admin -H "Content-Type: application/json" -d'{ "name" : "alice", "password" : "alice", "balance" : "20000" }' http://localhost:1337/accounts/alice

**Comment by adrianhopebailie** [comment]
I'd recommend getting onto the Gitter chat for support: https://gitter.im/interledger/Lobby

At first glance I think your issue is that you need to use that username and password to generate a token for HTTP Basic auth, not pass it in the request object.

**Comment by THEViveKL** [comment]
@adrianhopebailie 
how to get username and password
Thank for suggestion i have joined gitter for issue discussion.

**Comment by michielbdejong** [comment]
It seems the admin user is not being created on first run.

**Comment by sentientwaffle** [comment]
Admin user should be created when ledger starts (see [seed-db.js](https://github.com/interledgerjs/five-bells-ledger/blob/4b422ac64df302ee2e51014ef0f1745733001d97/src/lib/seed-db.js#L9)).

There is a typo in the README -- `ADMIN_PASSWORD` should be [`ADMIN_PASS`](https://github.com/interledgerjs/five-bells-ledger/blob/4b422ac64df302ee2e51014ef0f1745733001d97/src/lib/config.js#L40). That probably isn't the issue here, though, since the admin user/pass should just get set to the default values.

**Comment by michielbdejong** [comment]
This was fixed in #432, sorry for not closing this issue when that was merged.
